version: '3.7'

services:
  postgres_dashboard:
    build:
      context: postgres
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  postgres_test_dashboard:
    build:
      context: postgres
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_DB=postgres_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
